ALTER TABLE employees DROP COLUMN IF EXISTS "companyId" CASCADE;
ALTER TABLE contracts DROP COLUMN IF EXISTS "employeeId" CASCADE;
ALTER TABLE payrolls DROP COLUMN IF EXISTS "employeeId" CASCADE;
ALTER TABLE payroll_details DROP COLUMN IF EXISTS "payrollId" CASCADE;
ALTER TABLE leave_requests DROP COLUMN IF EXISTS "employeeId" CASCADE;
